//成交编号
export const execCodeArr = [
  {
    id: '2107',
    createUserId: 'admin',
    createUserName: null,
    createTime: '2020-04-26 00:24:08.000',
    updateUserId: null,
    updateUserName: null,
    updateTime: null,
    dicCode: '0',
    dicExplain: '现券买入',
    parentDicCode: '1030409',
    dicSort: 1,
    param1: null,
    param2: null,
    param3: null,
    paramExplain: null
  },
  {
    id: '2108',
    createUserId: 'admin',
    createUserName: null,
    createTime: '2020-04-26 00:24:08.000',
    updateUserId: null,
    updateUserName: null,
    updateTime: null,
    dicCode: '1',
    dicExplain: '现券卖出',
    parentDicCode: '1030409',
    dicSort: 2,
    param1: null,
    param2: null,
    param3: null,
    paramExplain: null
  },
  {
    id: '2109',
    createUserId: 'admin',
    createUserName: null,
    createTime: '2020-04-26 00:24:09.000',
    updateUserId: null,
    updateUserName: null,
    updateTime: null,
    dicCode: '2',
    dicExplain: '质押式正回购首期',
    parentDicCode: '1030409',
    dicSort: 3,
    param1: null,
    param2: null,
    param3: null,
    paramExplain: null
  },
  {
    id: '2110',
    createUserId: 'admin',
    createUserName: null,
    createTime: '2020-04-26 00:24:09.000',
    updateUserId: null,
    updateUserName: null,
    updateTime: null,
    dicCode: '3',
    dicExplain: '质押式正回购到期',
    parentDicCode: '1030409',
    dicSort: 4,
    param1: null,
    param2: null,
    param3: null,
    paramExplain: null
  },
  {
    id: '2111',
    createUserId: 'admin',
    createUserName: null,
    createTime: '2020-04-26 00:24:09.000',
    updateUserId: null,
    updateUserName: null,
    updateTime: null,
    dicCode: '4',
    dicExplain: '买断式正回购首期',
    parentDicCode: '1030409',
    dicSort: 5,
    param1: null,
    param2: null,
    param3: null,
    paramExplain: null
  },
  {
    id: '2112',
    createUserId: 'admin',
    createUserName: null,
    createTime: '2020-04-26 00:24:09.000',
    updateUserId: null,
    updateUserName: null,
    updateTime: null,
    dicCode: '5',
    dicExplain: '买断式正回购到期',
    parentDicCode: '1030409',
    dicSort: 6,
    param1: null,
    param2: null,
    param3: null,
    paramExplain: null
  },
  {
    id: '2113',
    createUserId: 'admin',
    createUserName: null,
    createTime: '2020-04-26 00:24:09.000',
    updateUserId: null,
    updateUserName: null,
    updateTime: null,
    dicCode: '6',
    dicExplain: '买断式逆回购首期',
    parentDicCode: '1030409',
    dicSort: 7,
    param1: null,
    param2: null,
    param3: null,
    paramExplain: null
  },
  {
    id: '2114',
    createUserId: 'admin',
    createUserName: null,
    createTime: '2020-04-26 00:24:09.000',
    updateUserId: null,
    updateUserName: null,
    updateTime: null,
    dicCode: '7',
    dicExplain: '买断式逆回购到期',
    parentDicCode: '1030409',
    dicSort: 8,
    param1: null,
    param2: null,
    param3: null,
    paramExplain: null
  },
  {
    id: '2120',
    createUserId: 'admin',
    createUserName: null,
    createTime: '2020-04-26 00:24:10.000',
    updateUserId: null,
    updateUserName: null,
    updateTime: null,
    dicCode: '13',
    dicExplain: '质押式逆回购首期',
    parentDicCode: '1030409',
    dicSort: 14,
    param1: null,
    param2: null,
    param3: null,
    paramExplain: null
  },
  {
    id: '2121',
    createUserId: 'admin',
    createUserName: null,
    createTime: '2020-04-26 00:24:10.000',
    updateUserId: null,
    updateUserName: null,
    updateTime: null,
    dicCode: '14',
    dicExplain: '质押式逆回购到期',
    parentDicCode: '1030409',
    dicSort: 15,
    param1: null,
    param2: null,
    param3: null,
    paramExplain: null
  },
  {
    id: '419',
    createUserId: 'admin',
    createUserName: null,
    createTime: '2020-08-05 09:30:06.000',
    updateUserId: null,
    updateUserName: null,
    updateTime: null,
    dicCode: '33',
    dicExplain: '债券借贷融入首期',
    parentDicCode: '1030409',
    dicSort: 34,
    param1: null,
    param2: null,
    param3: null,
    paramExplain: null
  },
  {
    id: '420',
    createUserId: 'admin',
    createUserName: null,
    createTime: '2020-08-05 09:30:06.000',
    updateUserId: null,
    updateUserName: null,
    updateTime: null,
    dicCode: '34',
    dicExplain: '债券借贷融入到期',
    parentDicCode: '1030409',
    dicSort: 35,
    param1: null,
    param2: null,
    param3: null,
    paramExplain: null
  },
  {
    id: '421',
    createUserId: 'admin',
    createUserName: null,
    createTime: '2020-08-05 09:30:06.000',
    updateUserId: null,
    updateUserName: null,
    updateTime: null,
    dicCode: '35',
    dicExplain: '债券借贷融出首期',
    parentDicCode: '1030409',
    dicSort: 36,
    param1: null,
    param2: null,
    param3: null,
    paramExplain: null
  },
  {
    id: '422',
    createUserId: 'admin',
    createUserName: null,
    createTime: '2020-08-05 09:30:06.000',
    updateUserId: null,
    updateUserName: null,
    updateTime: null,
    dicCode: '36',
    dicExplain: '债券借贷融出到期',
    parentDicCode: '1030409',
    dicSort: 37,
    param1: null,
    param2: null,
    param3: null,
    paramExplain: null
  },

];

//交易指令编号
export const tradeInstructIdArr = [
  {
    id: '2122',
    createUserId: 'admin',
    createUserName: null,
    createTime: '2020-04-26 00:24:10.000',
    updateUserId: null,
    updateUserName: null,
    updateTime: null,
    dicCode: '15',
    dicExplain: '现券内转买入',
    parentDicCode: '1030409',
    dicSort: 16,
    param1: null,
    param2: null,
    param3: null,
    paramExplain: null
  },
  {
    id: '2123',
    createUserId: 'admin',
    createUserName: null,
    createTime: '2020-04-26 00:24:10.000',
    updateUserId: null,
    updateUserName: null,
    updateTime: null,
    dicCode: '16',
    dicExplain: '现券内转卖出',
    parentDicCode: '1030409',
    dicSort: 17,
    param1: null,
    param2: null,
    param3: null,
    paramExplain: null
  },
  {
    id: '2132',
    createUserId: 'admin',
    createUserName: null,
    createTime: '2020-04-26 00:24:11.000',
    updateUserId: null,
    updateUserName: null,
    updateTime: null,
    dicCode: '25',
    dicExplain: '网上分销买入',
    parentDicCode: '1030409',
    dicSort: 26,
    param1: null,
    param2: null,
    param3: null,
    paramExplain: null
  },
  {
    id: '2133',
    createUserId: 'admin',
    createUserName: null,
    createTime: '2020-04-26 00:24:12.000',
    updateUserId: null,
    updateUserName: null,
    updateTime: null,
    dicCode: '26',
    dicExplain: '网下分销买入',
    parentDicCode: '1030409',
    dicSort: 27,
    param1: null,
    param2: null,
    param3: null,
    paramExplain: null
  },
  {
    id: '226',
    createUserId: 'admin',
    createUserName: null,
    createTime: '2020-04-26 00:24:12.000',
    updateUserId: null,
    updateUserName: null,
    updateTime: null,
    dicCode: '32',
    dicExplain: '债券转上市',
    parentDicCode: '1030409',
    dicSort: 27,
    param1: null,
    param2: null,
    param3: null,
    paramExplain: null
  },
  {
    id: '456',
    createUserId: 'admin',
    createUserName: null,
    createTime: '2020-08-05 09:30:06.000',
    updateUserId: null,
    updateUserName: null,
    updateTime: null,
    dicCode: '37',
    dicExplain: '现券回售',
    parentDicCode: '1030409',
    dicSort: 38,
    param1: null,
    param2: null,
    param3: null,
    paramExplain: null
  }
];

//付息兑付
export const cashArr = [
  {
    id: '225',
    createUserId: 'admin',
    createUserName: null,
    createTime: '2020-04-26 00:24:11.000',
    updateUserId: null,
    updateUserName: null,
    updateTime: null,
    dicCode: '31',
    dicExplain: '付息兑付',
    parentDicCode: '1030409',
    dicSort: 26,
    param1: null,
    param2: null,
    param3: null,
    paramExplain: null
  }
];
